# Generated by Django 5.1.6 on 2025-11-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_previousyearquestion_approved_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previousyearquestion',
            unique_together=set(),
        ),
    ]
