# Generated by Django 5.1.6 on 2025-11-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_previousyearquestion_paper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearquestion',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
